framework:
    messenger:
        transports:
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 3
                    delay: 5000
                    multiplier: 2
            failed: 'doctrine://default?queue_name=failed'

        failure_transport: failed

        buses:
            messenger.bus.default:
                middleware:
                    - doctrine_ping_connection
                    - doctrine_close_connection

        routing:
            Symfony\Component\Mailer\Messenger\SendEmailMessage: async
